# Based on: https://github.com/variar/klogg?tab=readme-ov-file#linux
---
- name: Ensure apt keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download klogg GPG key
  get_url:
    url: https://klogg.filimonov.dev/klogg.gpg.key
    dest: /tmp/klogg.gpg.key
    mode: '0644'

- name: Convert key to apt keyring format
  command: gpg --dearmor --yes --output /etc/apt/keyrings/klogg.gpg /tmp/klogg.gpg.key
  args:
    creates: /etc/apt/keyrings/klogg.gpg

# Unfortunatelly, there is no supported newest codename "noble", latest supported is "jammy"
# TODO: use {{ ubuntu_codename }} when it will be supported
- name: Add klogg apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/klogg.gpg] https://klogg.filimonov.dev/deb/jammy jammy utils"
    filename: klogg
    state: present

- name: Install klogg
  apt:
    name: klogg
    state: present
    update_cache: yes